apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
  namespace: opentelemetry
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      ## If uncommented, only service monitors with this label will get picked up
      # serviceMonitorSelector:
      #   app: my-app
  env:
    - name: NEW_RELIC_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: newrelic-key-secret
          key: new_relic_license_key
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]
        target_allocator:
          endpoint: http://otelcol-targetallocator.opentelemetry.svc.cluster.local
          interval: 30s
          collector_id: "${POD_NAME}"

    processors:
      batch:

    exporters:
      otlp/nr:
        endpoint: "otlp.nr-data.net:4317"
        tls:
          insecure: false
        headers:
          api-key: $NEW_RELIC_LICENSE_KEY
      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/nr, logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: []
          exporters: [otlp/nr, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/nr, logging]